#!/bin/bash

clear
echo Deleting all files in ./hiperpret
echo Running Hiperpret analysis, assuming that hiperMARK output data is present in ./instantiations.
echo Storing analysis results in ./hiperpret
echo Expecting one figure configs JSONs in this folder.

rm -rf hiperpret/
../hipermark/hiperpret -i ./instantiations/ -o ./hiperpret
