#!/bin/bash

clear
echo Deleting all files in instantiations/OptionPricing/
echo Running hipermark OptionPricing cpp_sequential and cpp_opencl small dataset, 4 times.
echo Storing all results in instantiations/

rm -rf instantiations/OptionPricing/
../hipermark/hipermark -o instantiations/ -n 4 -b benchmarks/OptionPricing -m cpp_sequential -m cpp_opencl -d small
