#!/bin/bash

clear
echo Deleting all files in instantiations/OptionPricing/
echo Running hipermark OptionPricing cpp_sequential and cpp_opencl small dataset, 4 times.
echo Storing all results in instantiations/

rm -rf instantiations/OptionPricing/
../hipermark/hipermark -o instantiations/ -n 30 -b benchmarks/OptionPricing -m cpp_opencl -m cpp_sequential -m cpp_openmp -d small -d medium -d large
