#ifndef OPTIMISATIONS
#define OPTIMISATIONS

#define _OPTIMIZATION_USE_FLOATS 1
#define _OPTIMIZATION_COST_MODEL_OR_FORCE_VECT_OR_FORCE_PRIV 0 // cost model: 0, vectorized: 1, privatized: 2
#define _OPTIMIZATION_SOBOL_STRENGTH_RED_RECURR
#define _OPTIMIZATION_MEM_COALES_ON

#endif // OPTIMISATIONS

