/* Monte-Carlo pricing code generated by LexiFi's MLFi compiler
   Compiler version: 3.12.1+dev4 (2010-09-03).
   Do not edit by hand! */
#include <mlfi_pricing.h>
static void trajectory(const mlfi_nmc_model* model) {
  double **underlyings = model->underlyings;

  model->notify_cash_flow(model, 0, fmax(0., ((underlyings[0][0] - 4000.) * model->deterministic_values[0])), 0 /*2012-11-30, 2012-11-30, EUR*/);
  return;

}
static void init(const mlfi_nmc_model* model) {
	//printf("Cosmin in void init!!!\n\n\n");
}
static mlfi_date state_dates[1]=
{17315280 /*2012-11-30*/};
static mlfi_cash_flow cash_flows[1]=
{{17315280 /*2012-11-30*/, 17315280 /*2012-11-30*/, EUR}};
static char* std_underlyings[1]=
{"DJ_Eurostoxx_50"};
static mlfi_nmc_deterministic_pricer deterministic_pricers[1]=
{{"(Zcb_risky(EUR, 2012-12-04, 1.))", 17315280 /*2012-11-30*/}};
static mlfi_nmc_pricing_code mc_info ={
 /*nb_contracts*/1,
 1, state_dates,
 1, cash_flows,
 1, std_underlyings,
 0, /*notify_parameters*/NULL,
 0, /*custom_pricers*/NULL,
 1, deterministic_pricers,
 /*only_initial_date_pricing*/0,
 /*size_of_pricing_data*/0,
 /*max_valuation_date*/168307199 /*2299-12-31T23:59:00*/,
 &init,
 &trajectory
};
MLFI_EXPORT mlfi_nmc_pricing_code* get_pricing_code(){return &mc_info;}
